development:
  adapter: postgresql
  encoding: unicode
  database: mythology_development
  pool: 5
  host: localhost
  username: chyld
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mythology_production
  pool: 5
  host: localhost
  username: chyld
  password:
